export declare const Syntax: {
    AssignmentExpression: string;
    ArrayExpression: string;
    BlockStatement: string;
    BinaryExpression: string;
    BreakStatement: string;
    CallExpression: string;
    CatchClause: string;
    ConditionalExpression: string;
    ContinueStatement: string;
    DoWhileStatement: string;
    DebuggerStatement: string;
    EmptyStatement: string;
    ExpressionStatement: string;
    ForStatement: string;
    ForInStatement: string;
    FunctionDeclaration: string;
    FunctionExpression: string;
    Identifier: string;
    IfStatement: string;
    Literal: string;
    LabeledStatement: string;
    LogicalExpression: string;
    MemberExpression: string;
    NewExpression: string;
    ObjectExpression: string;
    Program: string;
    Property: string;
    ReturnStatement: string;
    SequenceExpression: string;
    SwitchStatement: string;
    SwitchCase: string;
    ThisExpression: string;
    ThrowStatement: string;
    TryStatement: string;
    UnaryExpression: string;
    UpdateExpression: string;
    VariableDeclaration: string;
    VariableDeclarator: string;
    WhileStatement: string;
    WithStatement: string;
};
export declare function tokenize(code: any, options: any): any;
export declare function parse(code: any, options?: any): any;
export declare const version = "1.2.2";
